import bcrypt from 'bcryptjs';
import { User, Post, Follow, Like, Notification } from '../types/index.js';

// Pre-hashed 'password123'
const DEFAULT_HASH = bcrypt.hashSync('password123', 8);

export const initialUsers: User[] = [
  {
    id: 'user_knight',
    username: 'pixel_knight',
    display_name: 'Sir Galahad',
    bio: '⚔️ 8-bit Paladin of the Open Realm. Defender of clean pixels and turn-based coffee.',
    avatar_id: 'knight',
    banner_color: '#3a86ff',
    password_hash: DEFAULT_HASH,
    role: 'citizen' as const,
    created_at: '2026-08-01T10:00:00.000Z',
    followers_count: 42,
    following_count: 15,
  },
  {
    id: 'user_cat',
    username: 'cyber_cat',
    display_name: 'Neon Neko',
    bio: '🐾 Cyberpunk feline lurking on rooftops. I render in 60fps and nap in 240p. #pixelart',
    avatar_id: 'cat',
    banner_color: '#ff006e',
    password_hash: DEFAULT_HASH,
    role: 'citizen' as const,
    created_at: '2026-08-02T11:30:00.000Z',
    followers_count: 88,
    following_count: 24,
  },
  {
    id: 'user_wizard',
    username: 'arcane_wiz',
    display_name: 'Archmage Zephyr',
    bio: '🧙‍♂️ Casting CSS spells and compiling chiptune melodies. Level 99 Frontend Alchemist.',
    avatar_id: 'wizard',
    banner_color: '#8338ec',
    password_hash: DEFAULT_HASH,
    role: 'citizen' as const,
    created_at: '2026-08-03T09:15:00.000Z',
    followers_count: 65,
    following_count: 31,
  },
  {
    id: 'user_ninja',
    username: 'shadow_ninja',
    display_name: 'Kuro Shinobi',
    bio: '🥷 Slashing bugs silently in the night. Precision is key, both in katana and in pixels.',
    avatar_id: 'ninja',
    banner_color: '#1a1a24',
    password_hash: DEFAULT_HASH,
    role: 'citizen' as const,
    created_at: '2026-08-04T14:20:00.000Z',
    followers_count: 51,
    following_count: 19,
  },
  {
    id: 'user_bot',
    username: 'corgi_bot',
    display_name: 'Bit Corgi',
    bio: '🐶 Beep boop! The friendliest 16-bit canine on the network. Will fetch your tweets and your bones.',
    avatar_id: 'corgi',
    banner_color: '#fb5607',
    password_hash: DEFAULT_HASH,
    role: 'citizen' as const,
    created_at: '2026-08-05T08:00:00.000Z',
    followers_count: 120,
    following_count: 45,
  },
  {
    id: 'user_pilot',
    username: 'astro_pilot',
    display_name: 'Captain Nova',
    bio: '🚀 Exploring outer retro-space in a CRT starcruiser. Transmitting thoughts from Sector 7.',
    avatar_id: 'astronaut',
    banner_color: '#06d6a0',
    password_hash: DEFAULT_HASH,
    role: 'citizen' as const,
    created_at: '2026-08-06T16:45:00.000Z',
    followers_count: 73,
    following_count: 28,
  },
  {
    id: 'user_citizen_demo',
    username: 'citizen_demo',
    display_name: 'Citizen Demo',
    bio: 'Demo account for filing anonymous civic reports.',
    avatar_id: 'knight',
    banner_color: '#3a86ff',
    password_hash: DEFAULT_HASH,
    role: 'citizen',
    created_at: '2026-08-10T10:00:00.000Z',
    followers_count: 0,
    following_count: 0,
  },
  {
    id: 'user_gov_demo',
    username: 'gov_demo',
    display_name: 'Municipal Intelligence',
    bio: 'Government demo account. Use this panel to read clusters, not identities.',
    avatar_id: 'wizard',
    banner_color: '#8338ec',
    password_hash: DEFAULT_HASH,
    role: 'government',
    created_at: '2026-08-10T10:00:00.000Z',
    followers_count: 0,
    following_count: 0,
  },
];

export const initialPosts: Post[] = [
  {
    id: 'post_1',
    user_id: 'user_knight',
    content: 'Welcome to CivicPulse. File civic issues with a location — public cards stay anonymous.',
    created_at: '2026-08-17T08:30:00.000Z',
    likes_count: 18,
    replies_count: 3,
    reposts_count: 4,
  },
  {
    id: 'post_1_reply_1',
    user_id: 'user_cat',
    content: '@pixel_knight Working on custom CRT shaders for my 2D platformer! Everything looks 10x better with scanlines. 🐾 #gamedev',
    parent_post_id: 'post_1',
    created_at: '2026-08-17T08:45:00.000Z',
    likes_count: 8,
    replies_count: 1,
    reposts_count: 0,
  },
  {
    id: 'post_1_reply_1_sub',
    user_id: 'user_wizard',
    content: '@cyber_cat Scanlines are pure magic. Make sure to throw in a bit of chromatic aberration for full retro immersion! ✨',
    parent_post_id: 'post_1_reply_1',
    created_at: '2026-08-17T09:00:00.000Z',
    likes_count: 5,
    replies_count: 0,
    reposts_count: 0,
  },
  {
    id: 'post_1_reply_2',
    user_id: 'user_bot',
    content: '@pixel_knight Woof woof! I am busy collecting gold coins in dungeon level 4! 🐶🦴 #8bit',
    parent_post_id: 'post_1',
    created_at: '2026-08-17T09:10:00.000Z',
    likes_count: 12,
    replies_count: 0,
    reposts_count: 1,
  },
  {
    id: 'post_2',
    user_id: 'user_cat',
    content: 'Just finished polishing a 16x16 sprite animation loop! The key is keeping silhouette contrast super sharp. Never underestimate the power of a 1-pixel highlight. 🎨 #pixelart #sprites',
    created_at: '2026-08-17T11:15:00.000Z',
    likes_count: 29,
    replies_count: 2,
    reposts_count: 7,
  },
  {
    id: 'post_3',
    user_id: 'user_wizard',
    content: 'Hot take: 4-color palettes (like Game Boy DMG) force more creative ingenuity than 16-million RGB colors ever will. Limitations breed masterpieces. Agree or disagree? 💭 #retrogaming #indiedev',
    created_at: '2026-08-17T13:00:00.000Z',
    likes_count: 34,
    replies_count: 1,
    reposts_count: 6,
  },
  {
    id: 'post_4',
    user_id: 'user_pilot',
    content: 'Deep space telemetry report 🛰️: Just tuned into an 8-bit FM synthesis radio station drifting between Saturn and Jupiter. The bassline is absurdly good. #chiptune #8bit',
    created_at: '2026-08-17T14:45:00.000Z',
    likes_count: 22,
    replies_count: 0,
    reposts_count: 3,
  },
  {
    id: 'post_5_quote',
    user_id: 'user_ninja',
    content: 'Truth right here. When you only have 4 shades of olive green, every single pixel placement is tactical. 🗡️',
    quote_post_id: 'post_3',
    created_at: '2026-08-17T15:20:00.000Z',
    likes_count: 14,
    replies_count: 0,
    reposts_count: 2,
  },
];

export const initialFollows: Follow[] = [
  { follower_id: 'user_knight', following_id: 'user_cat', created_at: '2026-08-10T00:00:00.000Z' },
  { follower_id: 'user_knight', following_id: 'user_wizard', created_at: '2026-08-10T00:00:00.000Z' },
  { follower_id: 'user_knight', following_id: 'user_bot', created_at: '2026-08-10T00:00:00.000Z' },
  { follower_id: 'user_cat', following_id: 'user_knight', created_at: '2026-08-11T00:00:00.000Z' },
  { follower_id: 'user_cat', following_id: 'user_pilot', created_at: '2026-08-11T00:00:00.000Z' },
  { follower_id: 'user_wizard', following_id: 'user_ninja', created_at: '2026-08-12T00:00:00.000Z' },
  { follower_id: 'user_bot', following_id: 'user_knight', created_at: '2026-08-13T00:00:00.000Z' },
];

export const initialLikes: Like[] = [
  { user_id: 'user_cat', post_id: 'post_1', created_at: '2026-08-17T08:35:00.000Z' },
  { user_id: 'user_wizard', post_id: 'post_1', created_at: '2026-08-17T08:40:00.000Z' },
  { user_id: 'user_bot', post_id: 'post_1', created_at: '2026-08-17T08:50:00.000Z' },
  { user_id: 'user_knight', post_id: 'post_2', created_at: '2026-08-17T11:20:00.000Z' },
  { user_id: 'user_ninja', post_id: 'post_3', created_at: '2026-08-17T13:05:00.000Z' },
  { user_id: 'user_pilot', post_id: 'post_3', created_at: '2026-08-17T13:10:00.000Z' },
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif_1',
    recipient_id: 'user_knight',
    actor_id: 'user_cat',
    type: 'like',
    post_id: 'post_1',
    is_read: false,
    created_at: '2026-08-17T08:35:00.000Z',
  },
  {
    id: 'notif_2',
    recipient_id: 'user_knight',
    actor_id: 'user_cat',
    type: 'reply',
    post_id: 'post_1_reply_1',
    is_read: false,
    created_at: '2026-08-17T08:45:00.000Z',
  },
  {
    id: 'notif_3',
    recipient_id: 'user_knight',
    actor_id: 'user_bot',
    type: 'follow',
    is_read: true,
    created_at: '2026-08-13T00:00:00.000Z',
  },
];
